TutorProject/AdminsPanel/Controllers/EntitiesController.cs
using AdminsPanel.ViewModels;
using AdminsPanel.Validation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using TutorAdmin.Repositories;
using TutorAdmin.ViewModels;

namespace AdminsPanel.Controllers;

public class EntitiesController : Controller
{
    private readonly IEntityRepository<SpecialitiesViewModel> _repository;
    private readonly IEntityRepository<SubjectsViewModel> _srepository;
    private readonly EntitiesVMValidator _validator;
    private readonly SpecialitiesVMValidator _specValidator;
    public EntitiesController(IEntityRepository<SpecialitiesViewModel> repository, IEntityRepository<SubjectsViewModel> srepository, EntitiesVMValidator validator, SpecialitiesVMValidator specValidator)
    {
        _repository = repository;
        _srepository = srepository;
        _validator = validator;
        _specValidator = specValidator;
    }

    [HttpGet]
    public IActionResult GetEntity()
    {
        var subjects = _srepository.GetEntitiesAsync();
        var specialities = _repository.GetEntitiesAsync();

        EntitiesViewModel model = new EntitiesViewModel()
        {
            Specialities = specialities,
            Subjects = subjects
        };
        
        return View(model);
    }
    [HttpPost]
    public async Task<IActionResult> AddSpeciality([FromBody] SpecialitiesViewModel  specialitiesViewModel)
    {
        ValidationResult result = await _specValidator.ValidateAsync(specialitiesViewModel);
        var subjects = _srepository.GetEntitiesAsync();
        var specialities = _repository.GetEntitiesAsync();
        EntitiesViewModel model = new EntitiesViewModel()
        {
            Specialities = specialities,
            Subjects = subjects
        };
        if (!result.IsValid) 
        {
            result.AddToModelState(this.ModelState);


            
            // re-render the view when validation failed.
            return View("GetEntity", model);
        }

        _repository.CreateEntity(specialitiesViewModel); //Save the person to the database, or some other logic

        TempData["notice"] = "Person successfully created";
        return RedirectToAction("GetEntity");
    }
}

TutorProject/AdminsPanel/Controllers/TutorApplicationsController.cs
using AdminsPanel.Services.Application.Interfaces;
using AdminsPanel.ViewModels.Applications;
using Microsoft.AspNetCore.Mvc;
using Responses.DataTransferLib;
using Responses.DataTransferLib.TutorDtos;
using StatusCodes = Responses.Enums.StatusCodes;

namespace AdminsPanel.Controllers;

public class TutorApplicationsController : Controller
{
    private readonly IApplicationService _applicationService;
    private readonly ITutorService _tutorService;

    public TutorApplicationsController(IApplicationService applicationService, ITutorService tutorService)
    {
        _applicationService = applicationService;
        _tutorService = tutorService;
    }

    [HttpPost("/TutorApplications/Create")]
    public async Task<ActionResult<DefaultResponseObject<StatusCodes>>> Create(TutorAddDto request)
    {
        var response = await _applicationService.Add(request);

        return Ok(response);
    }

    [HttpGet]
    public IActionResult GetAllApplications()
    {
        var applications = _applicationService.GetAllApplications();
        return View(applications);
    }

    [HttpGet]
    public async Task<IActionResult> ApplicationInformation(string email)
    {
        try
        {
            var application = await _applicationService.GetAllApplicationFromEmail(email);
        
            return View(application);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return View(null);
        }
    }

    [HttpPost("/TutorApplications/Add")]
    public async Task<IActionResult> Create(AddApplicationViewModel model)
    {
        var result = await _applicationService.CreateTutor(model);
        var response = await _tutorService.AddTutor(result);
        if (response.Value != StatusCodes.ServiceOk) return Ok(StatusCodes.ServiceIsUnavailable);
        
        var statusCode = await _applicationService.UpdateApplication(model);
        return Ok(statusCode);
    }
    
    [HttpPost("/TutorApplications/Refuse")]
    public async Task<IActionResult> RefuseTutor(RefuseTutorDto model)
    {
        var checkApplication = await _applicationService.CheckApplication(model);
        if (!checkApplication) return Ok(StatusCodes.UserExists);
        var response = await _tutorService.RefuseTutor(model);
        if (response.Value != StatusCodes.ServiceOk) return Ok(StatusCodes.ServiceIsUnavailable);
      
        var application = await _applicationService.RefuseTutor(model);
        return Ok(application);
    }
}

TutorProject/AdminsPanel/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TutorAdmin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/TutorAdmin.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Entities" asp-action="GetEntity">TutorAdmin</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Entities" asp-action="GetEntity">Список сущностей</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Entities" asp-action="GetEntity">Пользователи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Entities" asp-action="GetEntity">Статистики</a>
                    </li>
                     <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="TutorApplications" asp-action="GetAllApplications">Прием репетиторов</a>
                         </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Только для администрации TUTOR
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/applicationsActions.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>